name: 🐞 Bug report
description: Report an issue
labels: [pending triage]
title: '`rule-name`: describe the bug here'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
          required: true
        - label: Read the [Contributing Guide](https://eslint.style/contribute/guide).
          required: true
        - label: Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
          required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      description: |
        The best reproduction would be a Pull Request adding new tests cases that make the CI fails. The test files are placed along side each rule's implemtation. You can learn how to setup your local environment [here](https://eslint.style/contribute/guide#local-setup).

        Otherwise, you can also [create a reproduction on Stackblitz](https://stackblitz.com/https://github.com/eslint-stylistic/repro-template). Create a new terminal and run `pnpm run play:lint` to see the lint result.

        A [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) is **required**, otherwise the issue might be closed without further notice. [**Why?**](https://antfu.me/posts/why-reproductions-are-required)
      placeholder: Reproduction
    validations:
      required: true
  - type: checkboxes
    id: contributes
    attributes:
      label: Contributes
      description: |
        As stylistic rules can be sometime subjective or niche, we may not have enough to maintainability to fix or improve every aspect.

        In general, **we encourage the original reporter to submit a PR to fix issue**. Check the following if you are willing to
      options:
        - label: I am willing to submit a PR to fix this issue
        - label: I am willing to submit a PR with failing tests
